### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by romainmartinez** [pyomeca/pyosim#14]
- pyosim
- pyomeca

**Comment by gurjarshakti** [comment]
hey @romainmartinez are you looking for logo ?

**Comment by romainmartinez** [comment]
Hi @gurjarshakti,

I planned to do it mysell, but a graphic designer would surely make a better job.

Contributions to our open source project are welcome, and they are greatly appreciated! Every little bit helps.

**Comment by gurjarshakti** [comment]
Well , I am graphics designer ( I am not sure but I am getting salary as a G.D. 😀 ). 
I will try my best.. tell me Little brief what you have plan for logo.. and which type logo you need. Some reference will make my job easy.

Thanks

**Comment by romainmartinez** [comment]
I did some tests and selected 5 fonts, 3 symbols and 4 colors.
In the following files, each line is a different font and each column is a different symbol.

- Color 1 (click to enhance):
![Color 1](https://rawgit.com/pyomeca/design/master/color_1.svg)
- Color 2 (click to enhance):
![Color 2](https://rawgit.com/pyomeca/design/master/color_2.svg)
- Color 3 (click to enhance):
![Color 3](https://rawgit.com/pyomeca/design/master/color_3.svg)
- Color 4 (click to enhance):
![Color 4](https://rawgit.com/pyomeca/design/master/color_4.svg)

@pariterre , any thoughts?

**Comment by romainmartinez** [comment]
my vote goes for this one
![logo](https://cdn.rawgit.com/pyomeca/design/e16443b9/logo.svg)

**Comment by pariterre** [comment]
I agree!

**Comment by romainmartinez** [comment]
Outline version
![logo](https://cdn.rawgit.com/pyomeca/design/1086046f/logo_outline.svg)
