### ISSUE TITLE
Not Run conda install pyosim -c pyomeca

### ISSUE THREAD

**Issue by jbarriosmuriel** [pyomeca/pyosim#28]
Not run the command "conda install pyosim -c pyomeca". I can't install pyosim.

**Comment by pariterre** [comment]
@jbarriosmuriel 
There is no host of pyosim on conda.. for now, you have to clone the repo and install it by yourself.
```bash
cd download_path
conda activate name_of_you_environment
python setup.py install
```
Please note that on my computer I have to comment, in the file enviroment.yml (using #) the line pyomeca and install it via conda.

**Comment by romainmartinez** [comment]
Pyosim is indeed on our anaconda repo. You just have to add conda-forge: `conda install pyosim -c conda-forge -c pyomeca`. We compiled opensim only for Linux OS btw.

**Comment by pariterre** [comment]
That is weird.. I tried to install prior to m my message and it didn't work... I probably made a typo, I'll have another try when I have access to my computer..
