### ISSUE TITLE
The example folder disapeared :(

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/pyosim#31]
@aceglia and @romainmartinez do you still have a  working example somewhere ?

**Comment by pariterre** [comment]
Don't think there were ever examples in this repo... Do the tests help?

**Comment by EveCharbie** [comment]
Aceglia gave me some pieces of code and I'll look at the tests. If I succeed, I might open a PR with an example.

**Comment by romainmartinez** [comment]
Hey @EveCharbie, have you looked at the docstrings? Most of the implemented code includes examples, such as in [inverse_dynamics.py](https://github.com/pyomeca/pyosim/blob/84b418ba276a9e5c499c44acd3fc4531103ad6c0/pyosim/inverse_dynamics.py#L36-L63).

**Comment by romainmartinez** [comment]
Oh, and the code I used to generate my analysis can be found here: [pyosim_aws](https://github.com/romainmartinez/pyosim_aws)

**Comment by EveCharbie** [comment]
That's perfect, thanks a lot !
